replicaCount: 2

image:
  repository: boicotaz/taskapp-frontend
  pullPolicy: Always
  tag: "5b8ff7d20fca98d068e360bed4238565f82d51dd"

service:
  type: ClusterIP
  port: 80

applicationPort: 80

ingress:
  enabled: true
  path: /
  pathType: Prefix

backend:
  serviceName: taskapp-backend
  servicePort: 80

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  requestsPerSecond: 5

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}