replicaCount: 2

image:
  repository: boicotaz/taskapp-frontend
  pullPolicy: Always
  tag: "8e5741627933ca5cfcd54daabe9d8476f35365a4"

service:
  type: ClusterIP
  port: 80

applicationPort: 80

ingress:
  enabled: true
  path: /
  pathType: Prefix

backend:
  serviceName: taskapp-backend
  servicePort: 80

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  requestsPerSecond: 5

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}