apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-seeder
  labels:
    app: {{ .Chart.Name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 5
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      restartPolicy: Never
      containers:
      - name: seeder
        image: postgres:15
        command: ["sh", "-c"]
        args:
          - |
            echo "Waiting..."
            until pg_isready -h {{ .Release.Name }} -U $POSTGRES_USER; do
              sleep 2
            done

            echo "Seeding..."
            psql -h {{ .Release.Name }} -U $POSTGRES_USER -d $POSTGRES_DB -f /seed/seed.sql
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: POSTGRES_USER
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: seed-volume
          mountPath: /seed
      volumes:
      - name: seed-volume
        configMap:
          name: {{ .Release.Name }}-seed-config
