apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Chart.Name }}
spec:
  encryptedData:
    POSTGRES_DB: {{ .Values.sealedSecrets.POSTGRES_DB }}
    POSTGRES_PASSWORD: {{ .Values.sealedSecrets.POSTGRES_PASSWORD }}
    POSTGRES_USER: {{ .Values.sealedSecrets.POSTGRES_USER }}